# Generated by Django 3.2.6 on 2021-11-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purplese', '0004_auto_20211125_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meusuario',
            name='imagem',
            field=models.ImageField(max_length=500, upload_to='static/img_upload'),
        ),
    ]
