# Generated by Django 3.2.6 on 2021-11-24 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purplese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meusuario',
            name='atualiza_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meusuario',
            name='criaca_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meusuario',
            name='imagem',
            field=models.ImageField(upload_to='static/img_upload'),
        ),
    ]
