# Generated by Django 3.2.6 on 2021-11-24 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purplese', '0002_auto_20211124_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='meusuario',
            name='nome',
            field=models.CharField(default=1, help_text='Entre com o Nome da sua imagem', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meusuario',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
